name = "BitManipulation"
uuid = "65be1bb9-2a0b-43ef-8e09-c8ff0aa270e9"
authors = ["bouddhaacelee <bouddhaacelee@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
